### ISSUE TITLE
The issues with the title Table Of Contents

### ISSUE THREAD

**Issue by s1-ranjan** [KTS915/Table-of-Contents#3]
As there are numerous languages but this plugin shows the index as Table Of Contents in every language from the front end, I would suggest to implement a text field under RENDER META BOX FOR HIDING TOC where one can input the index title in one's language and that text can be shown in the front end.
Secondly, The Table of Contents remains closed until it is clicked, So I would request to define a checkbox to remain open under RENDER META BOX FOR HIDING TOC so that one can control the behavior of the plugin at the front end from the editor's panel backend.

**Comment by KTS915** [comment]
These are great ideas. Thanks! But wouldn't it be better in each case to have one setting for all posts rather than have to set both things on every single post?

**Comment by KTS915** [comment]
Addressed by the above commits, which enable a user to choose their preferences on a global basis rather than per post.
